Basic: # 基础配置
  BotName: "xxxx" # 机器人在群里的名字
  MiraiPath: "/xxx/xxx/"  # Mirai根目录

  MAH: # Mirai HTTP API配置
    BotQQ: 123456 # 机器人QQ号
    MiraiHost: "http://xxxx:xxxx" # Mirai HTTP API地址
    MiraiAuthKey: "xxxxx" # Mirai HTTP API AuthKey

  Permission: # 权限管理
    Master: 123456 # 机器人主人QQ号
    MasterName: "xxxx" # 机器人主人昵称
    Admin: # 机器人管理员
      - 123456789

Saya: # saya 插件配置
  AzureTTS: # 阿里云文字转语音
    Disabled: false # 是否禁用
    # 密钥和区域获取地址：https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/overview#find-keys-and-region
    Subscription: "xxxxx" # 秘钥
    Region: "xxxxx" # 区域
  ChickDict: # 小鸡词典
    Disabled: false

  ChickEmoji: # 小鸡词典emoji翻译
    Disabled: false

  ChineseDict: # 汉典查询
    Disabled: false

  CloudMusic: # 网易云音乐点歌
    Disabled: false
    MusicInfo: true # 是否发送音乐信息

    ApiConfig: # 网易云Api搭建：https://github.com/Binaryify/NeteaseCloudMusicApi
      PhoneNumber: 123456 # 登录手机号码
      Password: "xxxx" # 登录密码

  CyberBlacktalk: # 网络黑话翻译
    Disabled: false

  WordCloud: # 词云生成
    Disabled: false

  MutePack: # 禁言套餐
    Disabled: false
    MaxTime: 3000 # 单倍最大时长
    MaxMultiple: 8 # 最大基础倍数
    MaxJackpotProbability: 10000 # 头奖概率 x分之一
    SuperDouble: true # 是否开启超级加倍
    MaxSuperDoubleProbability: 25 # 超级加倍概率 x分之一
    MaxSuperDoubleMultiple: 12 # 超级加倍最大倍数

  Beast: # 兽语转换
    Disabled: false
    BeastPhrase: # 兽语字符组，需要填写四个字符
      - "嗷"
      - "呜"
      - "啊"
      - "~"

  MinecraftPing: # Minecraft Server PING
    Disabled: false

  PetPet: # 摸头 GIF 生成
    Disabled: false
    CanAt: true # 是否可通过消息 at 触发
    CanNudge: true # 是否可通过戳一戳触发

  StyleLogoGenerator: # 风格 Logo 生成
    Disabled: false

  Repeater: # 复读机
    Disabled: false
    RepeatTimes: 3 # 复读所需次数
    Random:
      Disabled: false
      Probability: 260 # 默认复读概率 x分之一

  Pixiv: # 色图
    Disabled: false

  ChatMS: # 聊天？？
    Disabled: false

  Message: # 杂七杂八的回复
    Disabled: false

  DailyNewspaper: # 每日早报
    Disabled: false

  Setu: #色图
    Disabled: false

  AnitRecall: #防撤回
    Disabled: false

    Moderation:
      Disabled: false
      # 腾讯内容安全 API
      # 图片内容安全开通： https://console.cloud.tencent.com/cms
      # 文字内容安全开通： https://console.cloud.tencent.com/cms/text/overview
      # secret 获取地址： https://console.cloud.tencent.com/cam/capi
      secretId: "xxxxx"
      secretKey: "xxxxx"

  Entertainment: # 娱乐功能
    Disabled: false
    Lottery: true

  DiceMaid: # 骰娘
    Disabled: false

  BilibiliResolve: # B站解析
    Disabled: false

  VoiceMusicRecognition: # 听歌识曲
    Disabled: false
    # ACRCloud 音频识别 API
    # API 获取地址： https://cn-console.acrcloud.cn/service/avr
    original: # 原曲识别
      host: "xxxxx"
      access_key: "xxxxx"
      access_secret: "xxxxx"
    humming: # 哼唱识别
      host: "xxxxx"
      access_key: "xxxxx"
      access_secret: "xxxxx"

  Yinglish: #淫文翻译机
    Disabled: false

  EnglishTest: # 背单词
    Disabled: false

  BilibiliDynamic:
    Disabled: false
    Intervals: 60 # 间隔时间（秒）
    EnabledProxy: true # 启用代理
    Proxy: # 代理地址
      - http://127.0.0.1:1080
      
  CharacterDesignGenerator:
    Disabled: false

Final: false
# 配置完成后请调整为 true
# 配置完成后请调整为 true
# 配置完成后请调整为 true
